- name: variables from play level
  hosts: localhost
  vars: 
    course: "Devops"
    trainer: "siva kumar"
    duration: "3months"
  taks:
  - name: check variables
    ansible.builtin.debug:
      msg: "Hi, I am learning "{{course}}" and  the tutor is "{{trainer}}""
